
## Simple Usage

.Sample event definitions.
[source,nimrod]
type
  CommandEvent*   = object
  BreakfastEvent* = object
    eggs, pancakes: int

.Marking sample event objects as events.
[source,nimrod]
MakeIntoEvent CommandEvent
MakeIntoEvent BreakfastEvent

.Preparing IDs for commands.
[source,nimrod]
type
  ImportantCommands = enum
    icRequestBreakfast

.Transmitting events.
[source,nimrod]
----
# Enqueue a command for breakfast
myMap.Emit icRequestBreakfast, x
----

.Binding events to procedures
[source,nimrod]
----
proc HandleRequestForBreakfast(e: ptr Event[CommandEvent]) =
  # Enqueue breakfast
  var y = BreakfastEvent(eggs: 2, pancakses: 2)
  myMap.Emit y

myMap.On(CommandEvent, icRequestBreakfast, HandleRequestForBreakfast)
----

## Efficiency

UIDs are assigned at compile-time using macros, and are retrieved
through a static function. The optimizer should be able to remove this
overhead completely.

Events are triggered through a closure which adapts an event for use and
calls a second closure; at least one of these levels should be removed
by the optimizer (no guarantees.)

Currently the binding table is checked via linear search, using a single
machine `int` for comparison. If linear search proves to become a
bottleneck for the event queue, an adapted version which supports
looking up events via hash table (or consulting a static binding table)
are potential future enhancements.

## Garbage Collection

When sending an event, the object still remains on the call stack until
event processing has completed. Additionally, the object is only
referened to va internal pointers for the duration of the method calls.
Because of these two factors, the GC should work as per usual.

